version: '3.4'

services:
    slackbot_bs:
        image: 192.168.1.3:5000/hemna/slackbot_bs
        container_name: slackbot_bs
        user: 1000:1000
        ports:
            - 6000:6000
        restart: unless-stopped
