version: '3.4'


services:
    slackbot_bs:
        build:
          context: .
          dockerfile: Dockerfile
          tags:
            - "hemna6969/slackbot_bs:latest"
          platforms:
            - "linux/amd64"
            - "linux/arm64"
            - "linux/aarch64"
        image: hemna6969/slackbot_bs:latest
        container_name: slackbot_bs
        user: 1000:1000
        ports:
            - 3000:3000
        volumes:
            - ~/.config/slackbot_bs/slackbot_bs.conf:/tmp/slackbot_bs.conf
        restart: unless-stopped
        environment:
          - SLACK_SIGNING_SECRET=VALUE
          - SLACK_BOT_TOKEN=VALUE
